# Generated by Django 4.1.4 on 2022-12-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('subtitulo_detalles', models.CharField(max_length=100, verbose_name='Subtitulo')),
                ('texto', models.TextField(max_length=2000, verbose_name='Texto')),
            ],
        ),
    ]
